pool:
  vmImage: 'ubuntu-20.04'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.cache/.gradle
  SONAR_USER_HOME: $(Pipeline.Workspace)/.cache/.sonar
  imageName: felipebz/zpa-cli
  tag: nightly

steps:
  - checkout: self
    submodules: true

  - task: Cache@2
    inputs:
      key: 'gradle | "$(Agent.OS)" | **/build.gradle.kts'
      restoreKeys: |
        gradle | "$(Agent.OS)"
        gradle
      path: $(Pipeline.Workspace)/.cache

  - task: Gradle@2
    inputs:
      jdkVersionOption: 1.11
      tasks: "build publish"
      options: '--build-cache'
    env:
      DEPLOY_USERNAME: $(DEPLOY_USERNAME)
      DEPLOY_TOKEN: $(DEPLOY_TOKEN)

  - script: |
      # stop the Gradle daemon to ensure no files are left open (impacting the save cache operation later)
      ./gradlew --stop

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(system.defaultworkingdirectory)'
      contents: 'build/distributions/*'
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: zpa-cli

  - script: |
      ./source-test/run-sonar-scanner.sh
    displayName: 'Analyze demo project on SonarCloud'
    env:
      SONARCLOUD_ORGANIZATION: $(SONARCLOUD_ORGANIZATION)
      SONARCLOUD_TOKEN: $(SONARCLOUD_TOKEN)

  - task: Docker@2
    displayName: Build Docker image
    inputs:
      repository: $(imageName)
      command: build
      tags: |
        1.1.0
        $(tag)

  - task: Docker@2
    displayName: Push Docker image
    inputs:
      containerRegistry: DockerHub
      repository: $(imageName)
      command: push
      tags: |
        1.1.0
        $(tag)