pool:
  vmImage: 'ubuntu-20.04'

variables:
  imageName: felipebz/zpa-cli
  tag: 2

steps:
  - checkout: self
    submodules: true

  - task: Gradle@2
    inputs:
      jdkVersionOption: 1.11
      tasks: "build publish"
    env:
      DEPLOY_USERNAME: $(DEPLOY_USERNAME)
      DEPLOY_TOKEN: $(DEPLOY_TOKEN)

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(system.defaultworkingdirectory)'
      contents: 'build/distributions/*'
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: zpa-cli

  - script: |
      ./source-test/run-sonar-scanner.sh
    displayName: 'Analyze demo project on SonarCloud'
    env:
      SONARCLOUD_ORGANIZATION: $(SONARCLOUD_ORGANIZATION)
      SONARCLOUD_TOKEN: $(SONARCLOUD_TOKEN)

  - task: Docker@2
    displayName: Build Docker image
    inputs:
      repository: $(imageName)
      command: build
      tags: |
        $(tag)
        latest

  - task: Docker@2
    displayName: Push Docker image
    inputs:
      containerRegistry: DockerHub
      repository: $(imageName)
      command: push
      tags: |
        $(tag)
        latest